elfshaker as a C++ library
tipi-build/elfshaker pull request #11
Opened 2024-09-06 09:33 UTC by daminetreg

This provides support via our custom [corrosion-rs](https://github.com/tipi-build/corrosion/) of elshaker as a library.

This provide all functions that are really in use in tipi as direct C++ calls with the same signature as we are used to in tipi::cache::elfshaker in the nxxm-src codebase.

See : 
https://github.com/tipi-build/elfshaker/blob/1c1145bec7d207105e6253516bcb9ca11143295e/src/lib.rs#L53-L105

This is a work-in-progress, the main remaining parts are : 
- [ ] adapting CI to use cmake exclusively (instead of cargo)
- [ ] moving files back to their original location by playing with the namespaces use since I reinstated the lib type instead of only staticlib which doesn't auto provide the library to the app ( so that we can continue to benefit from official elfshaker patching)

## Requires review and merge of 

- [ ] https://github.com/tipi-build/corrosion/pull/2
   - [ ] Providing patch to upstream

2025-03-20 00:12 UTC, daminetreg commented
Now all tests pass on windows, macOS and linux

## windows
```
3:       Finished `release` profile [optimized] target(s) in 32.67s
3:        Running `C:/.tipi/vK.w/40999a5-elfshaker.b/b91cd2e/bin/x64/Release/cargo/build\release\deps\cli-cd5674971e4c89a5.exe`
3:   
3:   running 4 tests
3:   test package_file_see_status ... ok
3:   test symlink_to_directory ... ok
3:   test package_file_see_status_symlink ... ok
3:   test run_loosen_and_repack ... ok
3:
3:   test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.44s
3:
4/4 Test #3: cargo-test_cli ....................   Passed   36.37 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) =  36.44 sec

C:\Users\daminetreg\workspace\elfshaker>C:\tipi-for-arm-cmake-tipi-provider.exe . -t  vs-16-2019-win64-cxx17 -C Release -vv -n --test all  -- -A x64 -T host=x64 
```

## macOS
```
1: test repo::fs::tests::test_remove_empty_dirs_works ... ok
1: test repo::repository::tests::compute_entry_diff_finds_updates ... ok
1: test status::test::no_middle ... ok
1: test status::test::add_back ... ok
1: test repo::repository::tests::compute_entry_diff_finds_update_of_duplicated ... ok
1: test repo::repository::tests::building_loose_object_paths_works ... ok
1: test atomicfile::tests::test_atomic_update_api ... ok
1: test repo::algo::test::run_in_parallel_works ... ok
1: 
1: test result: ok. 33 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.22s
1: 
1: 
4/4 Test #1: cargo-test_elfshaker ..............   Passed    6.47 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) =   6.48 sec
➜  elfshaker git:(feature/elfshaker-as-a-library) ✗ tipi . -t clang-cxx17 -un --test all
```

## linux
```
3/4 Test #1: cargo-test_elfshaker ..............   Passed    9.02 sec
2:     Finished `test` profile [unoptimized + debuginfo] target(s) in 10.24s
2:      Running `/usr/local/share/.tipi/vK.w/40999a5-elfshaker.b/d53dd39/bin/./cargo/build/debug/deps/elfshaker_executable-8b17821f0d549e59`
2: 
2: running 0 tests
2: 
2: test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
2: 
4/4 Test #2: cargo-test_elfshaker_executable ...   Passed   10.31 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) =  10.31 sec
daminetreg@damien-ubuntu:~/workspace/elfshaker$ tipi . -t linux-cxx17 -un --test all
```

2025-04-03 08:07 UTC, Lambourl requested changes
Some small question or change. But the rust code is super clean

2025-04-03 08:07 UTC, Lambourl commented on .github/workflows/ci-cmake.yaml
> +          C:\Users\runneradmin\AppData\Local\tipi\tipi.exe . -t vs-16-2019-win64-cxx17 -C Release --dont-upgrade --verbose --use-cmakelists --test all
tipi should be on the path, please delete this long path

2025-04-03 08:07 UTC, Lambourl commented on .github/workflows/ci-cmake.yaml
> +          export HOME="/home/tipi"
give it in env to avoid repeat your self

2025-04-03 08:07 UTC, Lambourl commented on .tipi/distro.json
> +}
Did we need this file ? can we not use the distro or a modified distro with env var ?

2025-04-03 08:07 UTC, Lambourl commented on .vscode/settings.json
> +}
i thins you need to delete this file

2025-04-03 08:07 UTC, Lambourl commented on .tipi/opts.linux-cxx17
> +include_guard(GLOBAL)
For the first time, we protect our opts. Is it necessary?

2025-04-03 08:07 UTC, Lambourl commented on CMakeLists.txt
> +add_subdirectory(cmake/corrosion)
Why do you have remove fetchcontent and use submodule ?

2025-04-03 08:07 UTC, Lambourl commented on CMakeLists.txt
> +add_test(NAME test_cxxbridge COMMAND $<TARGET_FILE:test_cxxbridge>)
I will prefer to have it behind a `BUILD_TESTING` condition

2025-04-17 16:55 UTC, daminetreg commented on .github/workflows/ci-cmake.yaml
> +          C:\Users\runneradmin\AppData\Local\tipi\tipi.exe . -t vs-16-2019-win64-cxx17 -C Release --dont-upgrade --verbose --use-cmakelists --test all
It's not because the install script set the PATH In the other context not in that subshell. The install is not systemwide by default on windows.

2025-04-17 16:57 UTC, daminetreg commented on .tipi/distro.json
> +}
We need this and we don't have this file anywhere public otherwise. This is to represent the custom distro we use now with new environments in tipi, I need to update it though.

I could store it in the distro repo but it's for our own purpose not general.

2025-04-17 16:58 UTC, daminetreg commented on .tipi/opts.linux-cxx17
> +include_guard(GLOBAL)
No it's not

2025-04-17 16:59 UTC, daminetreg commented on CMakeLists.txt
> +add_subdirectory(cmake/corrosion)
Let's explain you this in a private channel

2025-04-17 17:02 UTC, daminetreg commented on CMakeLists.txt
> +add_test(NAME test_cxxbridge COMMAND $<TARGET_FILE:test_cxxbridge>)
Good point

2025-04-22 09:45 UTC, daminetreg commented on CMakeLists.txt
> +add_test(NAME test_cxxbridge COMMAND $<TARGET_FILE:test_cxxbridge>)
Done in [8eb7325](https://github.com/tipi-build/elfshaker/pull/11/commits/8eb73255d0fc508db8000374fcc28d0680334db3)

2025-04-29 12:35 UTC, daminetreg commented on .github/workflows/ci-cmake.yaml
> +          export HOME="/home/tipi"
I suspect the result might be different as we don't override the user here and when loading the shell there will be some .bashrc processing and it could overwite an env setting made more generally before. Therefore it's not clean but I will keep this in this iteration.

2025-04-29 12:54 UTC, pysco68 approved these changes
Thanks for the great work 🚀 

The few leftover calls the println() will be fixed in a subsequent PR

2025-04-29 13:13 UTC, Lambourl approved these changes
LGTM 
Thank you very much for your excellent work 👍

2025-04-29 13:16 UTC, merged